name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET Core 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Setup .NET Core 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: dotnet restore -p:TargetFramework=net6.0
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./src/Blazor-ApexCharts
